#!/usr/bin/bash

# CYCLE WALLPAPER USING SWWW

TMP="/tmp/current_wall"
WALLPAPERS=(~/.wallpapers/*)

i=$(cat $TMP)
i=$((i+1))

if [ $i -ge ${#WALLPAPERS[@]} ]; then
  i=0
fi

echo $i > $TMP
~/.config/hypr/scripts/wall "${WALLPAPERS[$i]}"
exit 0
