#!/bin/bash

function switch_theme() {
    local theme=$1
    
    if [ -d ~/.config/hypr/themes/$theme/pywal ]; then
        wal -f ~/.config/hypr/themes/$theme/pywal/$theme.json 
        kitty @set-colors --all ~/.cache/wal/colors-kitty.conf   
    else
        wal -i ~/.config/hypr/themes/$theme/wallpaper.png 
        kitty @ set-colors --all ~/.cache/wal/colors-kitty.conf
    fi

    ln -sf ~/.config/hypr/themes/$theme/waybar/config-bottom.jsonc ~/.config/waybar/config-bottom.jsonc 
    ln -sf ~/.config/hypr/themes/$theme/waybar/style-bottom.css ~/.config/waybar/style-bottom.css
    ln -sf ~/.config/hypr/themes/$theme/waybar/config.jsonc ~/.config/waybar/config.jsonc 
    ln -sf ~/.config/hypr/themes/$theme/waybar/style.css ~/.config/waybar/style.css

    # Link hypr styling config if exists
    if [ -f ~/.config/hypr/themes/$theme/hypr/styling.conf ]; then
        ln -sf ~/.config/hypr/themes/$theme/hypr/styling.conf ~/.config/hypr/styling.conf
    fi
    
    killall waybar 
    rm /tmp/waybar-bottom.pid
    rm /tmp/waybar.pid 


    # Check if /tmp/waybar.pid exists

    ~/.config/waybar/scripts/toggle_bottombar.sh &
    ~/.config/waybar/scripts/toggle_bar.sh &
    # Set kitty colors
    kitty @ set-colors --all ~/.cache/wal/colors-kitty.conf
    pywalfox update
    # Set gtk options
    while IFS= read -r line
    do
        key=$(echo $line | cut -d'=' -f1)
        value=$(echo $line | cut -d'=' -f2)
        gsettings set org.gnome.desktop.interface $key "$value"
    done < ~/.config/hypr/themes/$theme/gtk-settings.conf

    # Switch the wallpaper
    swww img ~/.config/hypr/themes/$theme/wallpaper.png



    # Show a notification
    notify-send -i terminal "Theme has been switched to $theme"
}

while getopts ":t:" opt; do
  case ${opt} in
    t )
      theme=$OPTARG
      ;;
    \? )
      echo "Invalid option: $OPTARG" 1>&2
      ;;
    : )
      echo "Invalid option: $OPTARG requires an argument" 1>&2
      ;;
  esac
done
shift $((OPTIND -1))

if [ -n "$theme" ]; then
    switch_theme $theme
else
    echo "Please specify a theme with -t"
fi
