#!/bin/bash

MSGID=29342834

status=$(bluetoothctl show | grep "Powered" | awk '{print $2}')

toggle_bluetooth() {
  if [[ $status == "yes" ]]; then
    bluetoothctl power off
    notify-send -a "bluetooth" -u low -i bluetooth -r $MSGID -t 2000 "Bluetooth disconnected!"
    echo "Bluetooth disconnected"
  else
    bluetoothctl power on
    notify-send -a "bluetooth" -u low -i bluetooth -r $MSGID -t 2000 "Bluetooth connected!"
    echo "Bluetooth connected!"
  fi
}

# Llamar a la función para alternar el estado de Bluetooth
toggle_bluetooth
