#!/usr/bin/bash
# Hyprland Startup Script

CNFG=$HOME/.config
WALLPAPER_DIR=$HOME/.wallpapers
START_WALLPAPER=$WALLPAPER_DIR/1.jpg

# SWWW Daemon (Wallpaper switcher)
swww-daemon

# Notification client
swaync &

# Clipboard Manager
copyq &

# Bluetooth GUI Helper
#blueman-manager &

# Load theme 
wal -f "$CNFG/wal/colorschemes/ju.json"

# Set wallpaper initially
swww img --transition-type grow --transition-pos 0.9,0.1 --transition-duration 3 $START_WALLPAPER

# Start Waybar
"$CNFG/waybar/scripts/toggle_bar.sh"

# Start authentication agent
/usr/lib/polkit-kde-authentication-agent-1 &

dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

# oddly enough, this is needed for me or no sound on launch
systemctl --user restart pipewire &
