#!/usr/bin/bash
# Hyprland Startup Script
CNFG=$HOME/.config

# Hyprpaper (Wallpaper switcher)
hyprpaper &

# Notification client
swaync & 

# Clipboard Manager
# copyq &

# Bluetooth Tray Icon
blueman-applet &

# Network Manager Tray Icon
nm-applet & 

# Load theme 
#wal -f "$CNFG/wal/colorschemes/ju.json" 

# Start Waybar
waybar -c $CNFG/waybar/config.jsonc -s $CNFG/waybar/style.css &
waybar -c $CNFG/waybar/config-bottom.jsonc -s $CNFG/waybar/style.css &

# Launch terminal apps
kitty --single-instance --title kitty_welcome
kitty --single-instance --title tty_clock --hold tty-clock -C6 

# Start authentication agent
/usr/lib/polkit-kde-authentication-agent-1 &

dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

# oddly enough, this is needed for me or no sound on launch
systemctl --user restart pipewire &
