

# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

windowrule = float on, match:title ^(file_progress|confirm|dialog|download|notification|error|splash|confirmreset|branchdialog)$
windowrule = float on, match:title ^(Open File|DevTools|Volume Control|Picture-in-Picture|Media viewer|nm-connection-editor|blueman-manager|copyq|pavucontrol|wlogout)$
windowrule = center on, match:title ^(confirm|dialog|download|confirmreset|file_progress|error|splash)$

# Specific rules for applications
windowrule = size 700 270, match:title ^(blueman-manager)
windowrule = center on, size (monitor_w*0.4) (monitor_h*0.4), match:title ^(copyq)
windowrule = fullscreen on, match:title ^(wlogout)$
windowrule = idle_inhibit focus, match:title ^(mpv)$
windowrule = idle_inhibit fullscreen, match:title ^(firefox)$
windowrule = fullscreen on, match:title wlogout
windowrule = size 800 600, move (75) ((monitor_h*0.44)), match:title ^(Volume Control)$

# Opacity 
windowrule = opacity 0.75, match:class ^(thunar)$
windowrule = opacity 0.7, match:class ^(vesktop)$
windowrule = opacity 0.9, match:class ^(firefox)$
windowrule = opacity 0.8, match:class kitty

# Kitty Terminals 
windowrule = animation windows, move (center), size 800 500, float on, match:title ^(kitty_float)$
windowrule = float on, size 320 200, move ((monitor_w*0.75)) ((monitor_h*0.05)), match:title ^(tty_clock)$
windowrule = animation slide right, float on, size 780 540, center on, match:title ^(ju@ANGKORWAT)$
windowrule = animation slide, float on, size 600 600, move ((monitor_w*0.02)) ((monitor_h*0.25)), match:title ^(kitty_welcome)$

# Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
workspace = w[t1], gapsout:0, gapsin:0
workspace = w[tg1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = border_size 0, rounding 0, match:float 0, match:workspace w[t1]
windowrule = border_size 0, rounding 0, match:float 0, match:workspace w[tg1]
windowrule = border_size 0, rounding 0, match:float 0, match:workspace f[1]
